version: "3.8"
services:
  mongodb:
    container_name: revamped_brains_dev_env_mongodb
    networks:
      - revamped_brains
    image: 'mongo'
    volumes: 
      - mongodb_data:/data/db
    env_file: 
      - ./env/mongodb.env
  backend:
    container_name: revamped_brains_dev_env_backend
    networks:
      - revamped_brains
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    image: revamped_brains_dev_env_backend
    ports:
      - '8000:8000'
      - '8001:8001'
    volumes: 
      - ./backend:/app
      - /app/node_modules
      - backend_logs:/app/logs
    stdin_open: true
    tty: true
    env_file: 
      - ./env/backend.env
    depends_on:
      - mongodb
  frontend:
    container_name: revamped_brains_dev_env_frontend
    networks:
      - revamped_brains
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    image: revamped_brains_dev_env_frontend
    ports: 
      - '3000:3000'
      - '3001:3001'
    volumes: 
      - ./frontend:/app
      - /app/node_modules
      - frontend_logs:/app/logs
    stdin_open: true
    tty: true
    env_file:
      - ./env/frontend.env
    depends_on: 
      - backend

volumes:
  mongodb_data:
    name: revamped_brains_dev_env_mongodb_data
  backend_logs:
    name: revamped_brains_dev_env_backend_logs
  frontend_logs:
    name: revamped_brains_dev_env_frontend_logs

networks:
  revamped_brains:
    name: revamped_brains_dev_env